name: ovsx-release

on:
  schedule:
    - cron: '0 1 1 */3 *'


env:
  NODE_VERSION: 20.14.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ env.NODE_VERSION}}

      - name: Update extension build number
        run: |
          commit_time=`git show --pretty=format:"%ci" | head -1`
          python -m nox -s update_build_number -- "$commit_time" release
          npm i -g ovsx

      - name: Publish release ovsx
        run: npm run ovsx-publish-release ${{ secrets.OPENVSX_ACCESS_TOKEN }}
        shell: bash