name: prerelease

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'bundled/**'
      - 'src/**'

env:
  NODE_VERSION: 16.19.0

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Use Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Pip lib cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-build-vsix-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-build-vsix-

      - name: Pip tool cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-build-vsix-${{ hashFiles('**/requirements-tool.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-build-vsix-tool

      - name: Upgrade pip
        run: python -m pip install -U pip
        shell: bash

      - name: Install build pre-requisite
        run: python -m pip install wheel
        shell: bash

      - name: Install nox
        run: python -m pip install nox
        shell: bash

      - name: Run npm ci
        run: npm ci --prefer-offline
        shell: bash

      - name: Install bundled python packages
        run: python -m nox -s install_package
        shell: bash

      - name: Update extension build number
        run: |
          commit_time=`git show --pretty=format:"%ci" | head -1`
          python -m nox -s update_build_number -- "$commit_time"

      - name: Publish prerelease VSIX
        run: npm run vsce-publish-prerelease ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
        shell: bash