name: prerelease

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'bundled/**'
      - 'src/**'
      - '!src/test/**'

env:
  NODE_VERSION: 20.14.0

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ env.NODE_VERSION}}

      - name: Update extension build number
        run: |
          commit_time=`git show --pretty=format:"%ci" | head -1`
          python -m nox -s update_build_number -- "$commit_time"

      - name: Publish prerelease VSIX
        run: npm run vsce-publish-prerelease ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
        shell: bash