name: release

on:
  schedule:
    - cron: '0 1 1 */3 *'


env:
  NODE_VERSION: 20.14.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ env.NODE_VERSION}}

      - name: Update extension build number
        run: |
          commit_time=`git show --pretty=format:"%ci" | head -1`
          python -m nox -s update_build_number -- "$commit_time" release

      - name: Publish release VSIX
        run: npm run vsce-publish-release ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
        shell: bash