name: test_scheduler

on:
  schedule:
    - cron: '0 * * * *'


env:
  NODE_VERSION: 16.19.0

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ env.NODE_VERSION}}

      - name: Update extension build number
        run: |
          commit_time=`git show --pretty=format:"%ci" | head -1`
          python -m nox -s update_build_number -- "$commit_time" release

      # - name: Publish prerelease VSIX
      #   run: npm run vsce-publish-release ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
      #   shell: bash